name: bcc-aux-blender-${dataset.scene}
tag: ""
seed: 42

dataset:
  name: blender
  scene: ???
  root_dir: ./load/nerf_synthetic/${dataset.scene}
  img_wh:
    - 800
    - 800
  # img_downscale: 1 # specify training image size by either img_wh or img_downscale
  near_plane: 2.0
  far_plane: 6.0
  train_split: "train"
  val_split: "val"
  test_split: "test"

model:
  name: bcc
  radius: 1.5
  num_samples_per_ray: 512
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 20000
  learned_background: false
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: bcc-sdf-with-aux
    radius: ${model.radius}
    grad_type: finite_difference
    finite_difference_eps: from_res
    isosurface:
      method: bcc-mt
      resolution: 128
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: BCCEncoding
      stored_data: "direct"
      rgb_basis_dim: 4
      feats_to_encode: 
        # - "alpha"
        # - "beta"
        - "density"
        # - "normals"
        - "latent_feats"
      scene_radius: 1.0
      latent_dims: 8
      grid_resolution: 128
      sh_n_bases: 1
      include_xyz: False
      pre_interpolation: True
      sphere_init_radius: 0.5
    aux_xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      # n_levels: 12
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      # per_level_scale: 2
      include_xyz: true
      start_level: 4
      start_step: 0
      update_steps: 1000
    mlp_network_config:
      otype: Identity
    aux_mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: false
      weight_norm: true
      small_init: true
  texture:
    name: bcc-radiance
    input_feature_dim: ${add:${model.geometry.xyz_encoding_config.latent_dims},3} # surface normal as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid

system:
  name: neus-system
  loss:
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 1.
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_curvature: 0.
    lambda_sparsity: 0.0
    lambda_distortion: 0.
    lambda_opaque: 0.
    lambda_laplacian_smoothness: 0.0
    lambda_aux_sdf_reg: 0.001
    sparsity_scale: 1.
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      variance:
        lr: 0.001
  constant_steps: 5000
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.constant_steps}
    schedulers:
      - name: ConstantLR
        args:
          factor: 1.0
          total_iters: ${system.constant_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.constant_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  chunk_size: 65536
  export_vertex_color: True

trainer:
  max_steps: 20000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 500
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
